[package]
name = "serde-transcode"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[dependencies]
serde = "0.8.0-rc3"

[dev-dependencies]
serde_json = "0.8.0-rc1"
serde_yaml = "0.4.0-rc1"
